In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [3]:
df=sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [6]:
print(df.sex.value_counts(),'\n\n',df.smoker.value_counts(),'\n\n',df.time.value_counts(),'\n\n',df.day.value_counts())

sex
Male      157
Female     87
Name: count, dtype: int64

 smoker
No     151
Yes     93
Name: count, dtype: int64

 time
Dinner    176
Lunch      68
Name: count, dtype: int64

 day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

## Feature Encoding

In [ ]:
## replce sex,smoker,time with 0 and 1 //label encoding
## replce day with 3 features (let them be sun,thur,fri) //one hot encoding



## Before encoding do train test split always otherwise you will have data leakage

### Train test split

In [7]:
X=df.drop('tip',axis=1)
y=df['tip']

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=42)

## Encoding

In [10]:
## label encoding
from sklearn.preprocessing import LabelEncoder
le1=LabelEncoder()
le2=LabelEncoder()
le3=LabelEncoder()

In [12]:
X_train['sex']=le1.fit_transform(X_train['sex'])
X_train['smoker']=le2.fit_transform(X_train['smoker'])
X_train['time']=le3.fit_transform(X_train['time'])

X_test['sex']=le1.transform(X_test['sex'])
X_test['smoker']=le2.transform(X_test['smoker'])
X_test['time']=le3.transform(X_test['time'])

In [13]:
## One hot encoding --- column transformer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct=ColumnTransformer(transformers=[('onehot',OneHotEncoder(drop='first'),[3])],remainder='passthrough')

In [14]:
X_train=ct.fit_transform(X_train)
X_test=ct.transform(X_test)

In [18]:
pd.DataFrame(X_test)

      0    1    2      3    4    5    6    7
0   1.0  0.0  0.0  19.82  1.0  0.0  0.0  2.0
1   0.0  1.0  0.0   8.77  1.0  0.0  0.0  2.0
2   0.0  1.0  0.0  24.55  1.0  0.0  0.0  4.0
3   1.0  0.0  0.0  25.89  1.0  1.0  0.0  4.0
4   0.0  0.0  1.0  13.00  0.0  1.0  1.0  2.0
..  ...  ...  ...    ...  ...  ...  ...  ...
56  0.0  1.0  0.0   7.25  1.0  1.0  0.0  2.0
57  1.0  0.0  0.0  17.82  1.0  0.0  0.0  2.0
58  0.0  1.0  0.0  17.26  1.0  0.0  0.0  3.0
59  1.0  0.0  0.0  15.69  1.0  1.0  0.0  3.0
60  0.0  1.0  0.0  29.85  0.0  0.0  0.0  5.0

[61 rows x 8 columns]

## Support Vector zregressor

In [48]:
from sklearn.svm import SVR
svr=SVR(kernel='rbf')
svr.fit(X_train,y_train)

SVR()

In [49]:
y_pred=svr.predict(X_test)
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
print('R2 score is :',r2_score(y_test,y_pred))
print('MAE is :',mean_absolute_error(y_test,y_pred))
print('MSE is :',mean_squared_error(y_test,y_pred))

R2 score is : 0.45785428237157455
MAE is : 0.6121971560820857
MSE is : 0.721284125313967

## Hyperparameter Tuning

In [52]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.svm import SVR

model = SVR()

param_grid = {
    'C': [0.1, 1, 10, 100, 1000],
    'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
    'kernel': ['rbf']
}

grid = RandomizedSearchCV(
    estimator=model,
    param_distributions=param_grid,
    verbose=2,
    cv=5,
    n_jobs=-1
)

grid.fit(X_train, y_train)

print("Best Parameters:", grid.best_params_)
print("Best Score:", grid.best_score_)

Fitting 5 folds for each of 10 candidates, totalling 50 fits
Best Parameters: {'kernel': 'rbf', 'gamma': 0.01, 'C': 10}
Best Score: 0.4359499198334825