In [2]:
import numpy as np
import pandas as pd

np.random.seed(123)

n_samples=1000
class_0_ratio=0.9
n_class_0=int(n_samples * class_0_ratio)
n_class_1=n_samples-n_class_0

In [3]:
n_class_0,n_class_1

(900, 100)

In [11]:
class_0=pd.DataFrame({
    'feature1': np.random.normal(loc=0,scale=1,size=n_class_0),
    'feature2': np.random.normal(loc=0,scale=1,size=n_class_0),
    'target':[0] * n_class_0
})
class_1=pd.DataFrame({
    'feature1':np.random.normal(loc=2,scale=1,size=n_class_1),
    'feature2':np.random.normal(loc=2,scale=1,size=n_class_1),
    'target':[1] * n_class_1
})

In [12]:
df=pd.concat([class_0,class_1]).reset_index(drop=True)

In [13]:
df

     feature1  feature2  target
0   -1.774224  0.285744       0
1   -1.201377  0.333279       0
2    1.096257  0.531807       0
3    0.861037 -0.354766       0
4   -1.520367 -1.120815       0
..        ...       ...     ...
995  2.677156  1.092048       1
996  2.963404  0.181955       1
997  1.621476  1.877267       1
998  3.429559  3.794486       1
999  3.532273  1.679490       1

[1000 rows x 3 columns]

In [15]:
df[df['target']==1]

     feature1  feature2  target
900 -0.643425  2.571923       1
901  1.551009  1.782767       1
902  1.641093  2.054318       1
903  2.133194  2.155998       1
904  1.355758  2.467810       1
..        ...       ...     ...
995  2.677156  1.092048       1
996  2.963404  0.181955       1
997  1.621476  1.877267       1
998  3.429559  3.794486       1
999  3.532273  1.679490       1

[100 rows x 3 columns]

In [ ]:
df['target'].value_counts()

array([900, 100])

## Upsampling

In [23]:
df_majority=df[df['target']==0]
df_minority=df[df['target']==1]

In [24]:
from sklearn.utils import resample
df_minority_updated=resample(df_minority,replace=True,
         n_samples=len(df_majority),
         random_state=42
         )

In [25]:
df_minority_updated.shape

(900, 3)

In [28]:
df_upsampled=pd.concat([df_minority_updated,df_majority])

In [31]:
df_upsampled.value_counts

<bound method DataFrame.value_counts of      feature1  feature2  target
951  2.905343  1.495151       1
992  2.000977  1.814833       1
914  1.927957  2.280911       1
971  2.819483  2.964646       1
960  2.456515  1.833528       1
..        ...       ...     ...
895 -0.896718  2.540514       0
896  0.812571 -0.082706       0
897  0.637361  0.444621       0
898  0.332712  1.896404       0
899  0.258237  0.237581       0

[1800 rows x 3 columns]>

## Downsampling

In [32]:
df_majority=df[df['target']==0]
df_minority=df[df['target']==1]

In [33]:
from sklearn.utils import resample
df_majority_updated=resample(df_majority,
         n_samples=len(df_minority),
         random_state=42
         )

In [34]:
df_downsampled=pd.concat([df_majority_updated,df_minority])

In [39]:
df_downsampled.target.value_counts()

target
0    100
1    100
Name: count, dtype: int64